[package]

name = "logger"
version = "0.0.1"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>", "Michael Reinhard <mcreinhard@gmail.com>"]
description = "Logging middleware for the Iron framework."
repository = "https://github.com/iron/logger"
license = "MIT"

[dependencies]
iron = "*"
time = "*"
term = "*"
