[package]

name = "mount"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
version = "0.0.7"
description = "Mounting middleware for Iron."
repository = "https://github.com/iron/mount"
documentation = "http://ironframework.io/doc/mount/index.html"
license = "MIT"
keywords = ["iron", "web", "handler", "routing"]

[dependencies]
iron = "*"
url = "*"
sequence_trie = "*"
