[package]

name = "iron"
version = "0.5.1"
description = "Extensible, Concurrency Focused Web Development in Rust."
readme = "README.md"
repository = "https://github.com/iron/iron"
documentation = "http://ironframework.io/doc/iron/"
license = "MIT"
authors = [
    "Jonathan Reem <jonathan.reem@gmail.com>",
    "Zach Pomerantz <zmp@umich.edu>",
    "Michael Sproul <micsproul@gmail.com>",
    "Patrick Tran <patrick.tran06@gmail.com>"
]

[lib]
name = "iron"
path = "src/lib.rs"

[features]
default = []
native-tls-example = ["hyper-native-tls"]

[dependencies]
typemap = "0.3"
url = "1.1"
plugin = "0.2"
modifier = "0.1"
error = "0.1"
log = "0.3"
conduit-mime-types = "0.7"
lazy_static = "0.2"
num_cpus = "1.0"
hyper = "0.10"
hyper-native-tls = { version = "0.2", optional = true }

[dev-dependencies]
time = "0.1"
mime = "0.2"
