[package]

name = "logger"
version = "0.1.0"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>", "Michael Reinhard <mcreinhard@gmail.com>"]
description = "Logging middleware for the Iron framework."
repository = "https://github.com/iron/logger"
keywords = ["iron", "web", "logger", "log", "timer"]
license = "MIT"

[dependencies]
iron = { version = "0.4", default-features = false }
term = "0.4"
