[package]

name = "iron"
version = "0.6.0"
description = "Extensible, Concurrency Focused Web Development in Rust."
readme = "README.md"
repository = "https://github.com/iron/iron"
documentation = "http://ironframework.io/doc/iron/"
license = "MIT"
authors = [
    "Jonathan Reem <jonathan.reem@gmail.com>",
    "Zach Pomerantz <zmp@umich.edu>",
    "Michael Sproul <micsproul@gmail.com>",
    "Patrick Tran <patrick.tran06@gmail.com>"
]

[lib]
name = "iron"
path = "src/lib.rs"

[features]
default = []
native-tls-example = ["native-tls"]

[dependencies]
typemap = "0.3"
url = "1.1"
plugin = "0.2"
mime_guess = "2.0.0-alpha.1"
modifier = "0.1"
log = "0.3"
num_cpus = "1.0"
hyper = "0.11"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
futures-cpupool = "0.1"
tokio-tls = "0.1.1"
native-tls = { version = "0.1.1", optional = true }

[dev-dependencies]
time = "0.1"
mime = "0.3"
