[package]

name = "mount"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
version = "0.1.0"

[lib]

name = "mount"
path = "src/lib.rs"

[dependencies.iron]

git = "https://github.com/iron/iron.git"

[dependencies.typemap]

git = "https://github.com/reem/rust-typemap.git"

[dependencies.trie]

git = "https://github.com/michaelsproul/rust-generic-trie.git"
