[package]

name = "iron"
version = "0.0.1"
authors = [
    "Jonathan Reem <jonathan.reem@gmail.com>",
    "Zach Pomerantz <zmp@umich.edu>",
    "Patrick Tran <patrick.tran06@gmail.com>",
    "Michael Reinhard <mcreinhard@gmail.com>"]

[lib]

name = "iron"
path = "src/lib.rs"

[dependencies.http]

git = "https://github.com/chris-morgan/rust-http.git"

[dependencies.typemap]

git = "https://github.com/reem/rust-typemap.git"

[dependencies.content_type]

git = "https://github.com/reem/rust-http-content-type.git"

[dependencies.url]

git = "https://github.com/servo/rust-url.git"

[dependencies.plugin]

git = "https://github.com/reem/rust-plugin.git"

[dependencies.modifier]

git = "https://github.com/reem/rust-modifier.git"

[dependencies.error]

git = "https://github.com/reem/rust-error.git"

