[package]

name = "persistent"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
version = "0.3.0"
description = "A set of middleware for sharing server-global data in Iron."
repository = "https://github.com/iron/persistent"
documentation = "http://ironframework.io/doc/persistent/index.html"
license = "MIT"
keywords = ["iron", "web", "persistence", "sharing", "global"]

[dependencies]
iron = "0.5"
plugin = "0.2"
